### ISSUE TITLE
Pulse implementation missing new attributes

### ISSUE THREAD

**Issue by jstr** [mort666/otx_ruby#1]
In recent changes to the AlienVault OTX API `TLP`, `public`, `in_group`, `group_id`,  `group_name`, and `groups` attributes have been added to the Pulse JSON data.

Because this Gem does not know about these new attributes, fetching subscribed pulses results in the following exception:

```
NoMethodError: undefined method `TLP=' for #<OTX::Pulse:0x007f81229fd0a8>
~/otx_ruby/lib/otx_ruby/types/pulse.rb:22:in `block in initialize'
~/otx_ruby/lib/otx_ruby/types/pulse.rb:20:in `each'
~/otx_ruby/lib/otx_ruby/types/pulse.rb:20:in `initialize'
~/otx_ruby/lib/otx_ruby/subscribed.rb:29:in `new'
~/otx_ruby/lib/otx_ruby/subscribed.rb:29:in `block in get_all'
~/otx_ruby/lib/otx_ruby/subscribed.rb:28:in `each'
~/otx_ruby/lib/otx_ruby/subscribed.rb:28:in `get_all'
```

This is seen both in `master` and Gem version `0.5.2` (latest).

**Comment by mort666** [comment]
I've integrated your pull request which looks like it will deal with these. I've updated the fixtures and pushed the gem with the fix.

Thanks..
